name: Demo MMDT
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  demo-mmdt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Print Weather API secret
        run: echo ${{ secrets.WEATHER_KEY}}
      - name: Run ETL pipeline
        run: python project/main.py
        env:
          WEATHER_KEY: ${{secrets.WEATHER_KEY}}
      - name: Push changes to save as City_Weather_Covid_Data.xlsx
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@users.noreply.github.com"
          git add ./City_Weather_Covid_Data.xlsx
          git commit -m "Push City_Weather_Covid_Data.xlsx from demo" && git push || true